# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    app.repository.currency:
        class: AppBundle\EntityRepository\CurrencyRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Currency

    app.repository.merchant:
        class: AppBundle\EntityRepository\MerchantRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Merchant

    app.repository.transaction:
        class: AppBundle\EntityRepository\TransactionRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Transaction

    app.services.import_csv:
        class: AppBundle\Services\ImportCsv
        arguments: ['@app.repository.currency', '@app.repository.merchant']

    app.command.app_import_csv_command:
        class: AppBundle\Command\AppImportCsvCommand
        arguments: ['@app.services.import_csv', '@app.repository.transaction']
        tags:
            - { name: console.command }
